/**
 * Supabase database types
 * 
 * This file will be auto-generated by Supabase CLI
 * For now, we'll define basic types manually
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users_profile: {
        Row: {
          id: string;
          name: string | null;
          surname: string | null;
          image: string | null;
          is_anonymous: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name?: string | null;
          surname?: string | null;
          image?: string | null;
          is_anonymous?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string | null;
          surname?: string | null;
          image?: string | null;
          is_anonymous?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      prayer_logs: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          prayer_name: string;
          status: 'completed' | 'missed' | 'pending';
          logged_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          prayer_name: string;
          status: 'completed' | 'missed' | 'pending';
          logged_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          prayer_name?: string;
          status?: 'completed' | 'missed' | 'pending';
          logged_at?: string;
          created_at?: string;
        };
      };
      push_tokens: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          platform: 'ios' | 'android';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          platform: 'ios' | 'android';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          token?: string;
          platform?: 'ios' | 'android';
          created_at?: string;
          updated_at?: string;
        };
      };
      duas: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          text: string;
          is_favorite: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          title: string;
          text: string;
          is_favorite: boolean;
          created_at: string;
          updated_at: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          text?: string;
          is_favorite?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_settings: {
        Row: {
          id: string;
          user_id: string;
          prayer_method: string;
          notification_settings: Json;
          location: Json | null;
          daily_verse_enabled: boolean;
          daily_verse_time: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          prayer_method?: string;
          notification_settings?: Json;
          location?: Json | null;
          daily_verse_enabled?: boolean;
          daily_verse_time?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          prayer_method?: string;
          notification_settings?: Json;
          location?: Json | null;
          daily_verse_enabled?: boolean;
          daily_verse_time?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_today_prayer_log: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      update_prayer_status: {
        Args: {
          p_prayer_name: string;
          p_status: string;
        };
        Returns: void;
      };
      get_prayer_streak: {
        Args: Record<PropertyKey, never>;
        Returns: number;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

